---
- hosts: app
  become: yes
  roles:
    - docker-role

  tasks:
    - name: Убедиться, что git установлен
      become: yes
      apt:
        name: git
        state: present
        
    - name: start
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: timurbabs/django
        state: started
        restart_policy: always
        ports:
          - "{{ container_ports }}"

- hosts: web
  become: yes
  vars:
    proxy_pass: "http://192.168.56.203:8000"
  roles:
    - nginx-role