---
- name: docker-role
  src: https://gitlab.com/ansible-roles9394643/docker-role/
  scm: git
  version: main

- name: nginx-role
  src: https://gitlab.com/ansible-roles9394643/nginx-role/
  scm: git
  version: main
